<?php

/**
* Implements hook_form_alter().
*/

function first_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  if($form_id = 'user-login-form'){
    $form['#title'] = t('Login with your info');
    $form['name']['#attributes']['placeholder']= t('Enter your username here');
    $form['pass']['#attributes']['placeholder']= t('Enter your password here');
  }

}



/**

* Implements hook_preprocess_page().

**/
 
function first_module_preprocess_page(&$variables) {

    $variables['first_module_variable'] = 'My First D10 Module';

}
 
?>